# Generated by Django 2.2.6 on 2019-10-29 10:30
from datetime import date
from django.db import migrations, transaction


def populate_expiration_date_2(apps, schema_editor):
    """
    Convert DateTime data from expiration_date to Date format
    and save into temp field expiration-date_2
    """
    Menu = apps.get_model('menu', 'Menu')

    for menu in Menu.objects.all():
        if menu.expiration_date:
            menu.expiration_date_2 = menu.expiration_date.date()
            with transaction.atomic():
                menu.save()


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menu_expiration_date_2'),
    ]

    operations = [
        migrations.RunPython(populate_expiration_date_2)
    ]
