# Generated by Django 2.2.6 on 2019-10-29 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20191029_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='expiration_date_old',
        ),
    ]
