# Generated by Django 2.2.6 on 2019-10-31 08:54
import datetime
from django.db import migrations, transaction


def bulk_change_expiration_dates(apps, schema_editor):
    """
    Change all Menus with expiration date of '2021-10-24' to
    '2018-10-24'.
    """
    Menu = apps.get_model('menu', 'Menu')

    for menu in Menu.objects.all():
        if menu.expiration_date == datetime.datetime.strptime("2021-10-24", "%Y-%m-%d").date():
            menu.expiration_date = menu.expiration_date - datetime.timedelta(days=1096)
            with transaction.atomic():
                menu.save()


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_remove_menu_expiration_date_old'),
    ]

    operations = [
        migrations.RunPython(bulk_change_expiration_dates)
    ]
