# Generated by Django 2.2.7 on 2019-11-04 12:27

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20191031_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='expiration_date',
            field=models.DateField(blank=True, default=datetime.date.today()),
        ),
    ]
